CREATE TABLE USERS_WEBAPP (
    USER_ID NUMBER(10) CONSTRAINT ID_USER_NN NOT NULL,
    USER_NAME VARCHAR2(20) CONSTRAINT NAME_USER_NN NOT NULL,
    USER_EMAIL VARCHAR2(50) CONSTRAINT EMAIL_USER_NN NOT NULL,
    USER_PASSWORD VARCHAR2(200) CONSTRAINT PASSWORD_USER_NN NOT NULL,
    CONSTRAINT PK_USERS_WEBAPP PRIMARY KEY(USER_ID)
);

CREATE TABLE ROLES_WEBAPP (
    ROLE_ID NUMBER(10) CONSTRAINT ID_ROLE_NN NOT NULL,
    ROLE_NAME VARCHAR2(10) CONSTRAINT NAME_ROLE_NN NOT NULL,
    CONSTRAINT PK_ROLES_WEBAPP PRIMARY KEY(ROLE_ID)
);

CREATE TABLE USER_ROLE (
    USER_ID NUMBER(10) CONSTRAINT UR_ID_USER_NN NOT NULL,
    ROLE_ID NUMBER(10) CONSTRAINT UR_ID_ROLE_NN NOT NULL,
    CONSTRAINT PK_USER_ROLE PRIMARY KEY(USER_ID, ROLE_ID),
    CONSTRAINT FK_UR_USER_ID FOREIGN KEY(USER_ID) REFERENCES USERS_WEBAPP(USER_ID),
    CONSTRAINT FK_UR_ROLE_ID FOREIGN KEY(ROLE_ID) REFERENCES ROLES_WEBAPP(ROLE_ID)
);

ALTER TABLE USERS_WEBAPP 
ADD CONSTRAINT UNIQUE_USER_EMAIL UNIQUE(USER_EMAIL);

ALTER TABLE USERS_WEBAPP
ADD CONSTRAINT UNIQUE_USER_NAME UNIQUE(USER_NAME);

